### ISSUE TITLE
App lockup on share IOS

### ISSUE THREAD

**Issue by anarchopossum** [wrngwrld/Chanyan#21]
If a user opens an image on a thread and presses the share icon for the first time. The device will ask about sharing images. If the user sets "select photos", The app will always freeze when the user clicks download on the share menu when viewing an image

**Comment by wrngwrld** [comment]
I'll look into it, thanks

**Comment by wrngwrld** [comment]
Fixed this issue in Release [v0.8.2](https://github.com/wrngwrld/Chanyan/releases/tag/v0.8.2)
