### ISSUE TITLE
mp4 video replies not working

### ISSUE THREAD

**Issue by Romern** [wrngwrld/Chanyan#27]
mp4s currently only show a black screen, probably because videos are rendered only if they are webm:
https://github.com/wrngwrld/Chanyan/blob/ab69185c64468e7943415a1077e5373f73731b06/lib/pages/thread/thread_replies.dart#L52-L61

**Comment by wrngwrld** [comment]
You are totally right, thank you! I'll fix it in the next couple of days :)

**Comment by wrngwrld** [comment]
This issue got fixed in the newest release. This version should be available on testflight in the next days
