### ISSUE TITLE
Video Scrubbing makes it impossible to Swipe to next media

### ISSUE THREAD

**Issue by SimplyAnotherAnon** [wrngwrld/Chanyan#29]
Video attached below, I don't know if this was intentional - but it would probably be best if video Scrubbing only activated when on the progress bar, and otherwise keeping the swipe gestures to go back/forth in the gallery. 

https://github.com/user-attachments/assets/1f1adaa2-897d-4dd6-a447-1d9ccf169703

Thanks for all the updates!

**Comment by wrngwrld** [comment]
Thanks for the issue. Try swiping from bottom to top to change the video :) But I'll look into the scrubbing to see if I can make it better

**Comment by wrngwrld** [comment]
I actually had the left to right swiping implemented for the longest time. But when it came to implementing the scrubbing, I didn't really knew how to make it work with the swiping 😄
